# Project metadata
site_name: Odoo API Reference
site_url: https://lanhild.github.io/odoo-api-docs
site_author: Lanhild
site_description: >-
  Unofficial Odoo JSON-RPC HTTP API documentation made by @Lanhild for the community.
repo_name: Lanhild/odoo-api-docs
repo_url: https://github.com/Lanhild/odoo-api-docs
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 by @Lanhild. Community-driven documentation.

# Theme configuration
theme:
  font:
    text: Be Vietnam Pro
    code: MesloLGS NF
  
  favicon: images/favicon.png

  logo: images/logo.svg

  icon:
    repo: fontawesome/brands/github
  
  name: material

  palette:
    - scheme: default
      primary: custom
      accent: custom

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Customization
extra:
  generator: false
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/konvergo-apps
      name: Konvergo on Github
    - icon: material/web
      link: https://konvergo.com

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

# Page tree
nav:
  - Introduction: 
    - index.md
    - Getting started: starting.md
    - Authentication: authentication.md
  - Core Resources:
    - CRUD Operations:
        - Create: core/crud/create.md
        - Delete: core/crud/delete.md
        - Read: core/crud/read.md
        - Search: core/crud/search.md
        - Search Count: core/crud/search-count.md
        - Search Operators: core/crud/search-operators.md
        - Update: core/crud/update.md
    - Database Actions:
        - Create: core/database/create.md
        - Drop: core/database/drop.md
        - Dump: core/database/dump.md
        - Duplicate: core/database/duplicate.md
        - Restore: core/database/restore.md
        - List: core/database/list.md
        - Migrate: core/database/migrate.md
        - Rename: core/database/rename.md
        - Restore: core/database/restore.md
    - Server Actions:
        - Change admin password: core/server/change-admin-passwd.md
        - Check database existence: core/server/db-exist.md
        - Get server version: core/server/version.md
    
extra_css:
  - stylesheets/extra.css
