# Project metadata
site_name: Odoo API Reference
site_url: https://lanhild.github.io/odoo-jsonrpc
site_author: Lanhild
site_description: >-
  Unofficial Odoo JSON-RPC HTTP API documentation made by @Lanhild for konvergo.com and the community.
repo_name: konvergo-apps/odoo-jsonrpc
repo_url: https://github.com/konvergo-apps/odoo-jsonrpc
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 by @Lanhild for Konvergo

# Theme configuration
theme:
  font:
    text: Be Vietnam Pro
    code: MesloLGS NF
  
  favicon: images/favicon.png

  logo: images/logo.svg

  icon:
    repo: fontawesome/brands/github
  
  name: material

  palette:
    - scheme: default
      primary: custom
      accent: custom

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Customization
extra:
  generator: false
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/konvergo-apps
      name: Konvergo on Github
    - icon: material/web
      link: https://konvergo.com

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

# Page tree
nav:
  - Welcome: index.md
  - Getting started:
    - Common parameters: common/common-parameters-in-a-request.md
    - Authentication:
        - Login to a given database: authentication/how-to-login-to-a-given-database.md
  - Requests:
      - CRUD operations:
          - Create a record: requests/create.md
          - Read a record: requests/read.md
          - Update a record: requests/update.md
          - Delete a record: requests/delete.md
    
extra_css:
  - stylesheets/extra.css